### ISSUE TITLE
ucrel.corpus.csv

### ISSUE THREAD

**Issue by agoodStu** [DavidSouto/eye-writing-task#3]
Hi, DavidSouto
I would like to use this program in my study for testing. I don't find `'ucrel.corpus.csv' ` in Github repository.  I got a words frequency list from `http://ucrel.lancs.ac.uk/bncfreq/`.  It's can't run by code below.
```
    fid=fopen('ucrel.corpus.csv');
    WORDS = textscan(fid,'%s %d %s','delimiter',',');
    fclose(fid);
```
So, I think my data structure is wrong. Could you give me a sample about `'ucrel.corpus.csv' ` please? That would help me a lot. 
Thank you.

**Comment by DavidSouto** [comment]
Hi Glad to see somebody is using the code. That was an oversight. I am attaching the list we used here. If I remember well we edited it so there was no six-letter words with repeated letters. This should work. Please let me know otherwise.
[ucrel.corpus.csv](https://github.com/DavidSouto/eye-writing-task/files/7097603/ucrel.corpus.csv)

David

**Comment by agoodStu** [comment]
> Hi Glad to see somebody is using the code. That was an oversight. I am attaching the list we used here. If I remember well we edited it so there was no six-letter words with repeated letters. This should work. Please let me know otherwise.
> [ucrel.corpus.csv](https://github.com/DavidSouto/eye-writing-task/files/7097603/ucrel.corpus.csv)
> 
> David

Hi, David
Thanks for your reply. After I use this file, the program is ready to run. And I got another question when I set `controlMode = 1`. During the presentation of the target word, the virtual keyboard could display [correctly.](https://imgtu.com/i/h6RIgJ) But after I pressed `Enter` to next phase, the virtual keyboard disappeared and my gaze drew something on screen like [this.](https://imgtu.com/i/h6WtxJ) The program reported no errors. When I set `controlMode = 0`, it worked fine.

Could you give me some advice? If you need more information, please let me know.

**Comment by DavidSouto** [comment]
Hi This is made to work with the eyelink eye tracker, it would require many adjustments for other eyetracker. Is that something you are using? I also realize from your screen copy indicates that I have mistakenly uploaded an old version of the program. I'll try uploading the last version today in case that was the problem.

**Comment by DavidSouto** [comment]
I realize from your screen copy that I uploaded an older version of the experiment. I wonder if that's the problem. I'll try uploading the intended version today.

**Comment by DavidSouto** [comment]
I am away from the lab so I couldn't check properly but the version I uploaded should be right. Let me know if it doesn't work. Now the filtered version of the word database is called (corpus folder)

**Comment by agoodStu** [comment]
Hi, David
I tested the code you uploaded and it worked fine.  It helps me saving a lot of time and makes me have enough time to study.
Thank you for your help.  I'll close the issues. 
Best wishes.

**Comment by DavidSouto** [comment]
That's great. Thanks for letting me know.
